import { useState } from 'react'
import { useNavigate } from 'react-router-dom'

export default function Report({ data, apiBase }) {
    const navigate = useNavigate()
    const [ceoEmail, setCeoEmail] = useState('')
    const [sending, setSending] = useState(false)
    const [toast, setToast] = useState(null)

    if (!data) {
        return (
            <div className="page" style={{ textAlign: 'center', paddingTop: '120px' }}>
                <h2>No Analysis Data</h2>
                <p style={{ color: 'var(--text-secondary)', marginTop: '8px' }}>Analyze a repository first.</p>
                <button className="btn btn-primary" style={{ marginTop: '20px' }} onClick={() => navigate('/')}>← Go Home</button>
            </div>
        )
    }

    const report = data.report || {}
    const metrics = report.metrics || {}

    const showToast = (message, type = 'success') => {
        setToast({ message, type })
        setTimeout(() => setToast(null), 4000)
    }

    const sendEmail = () => {
        if (!ceoEmail.trim() || !ceoEmail.includes('@')) {
            showToast('Please enter a valid email address', 'error')
            return
        }

        const reportText = report.report_text || 'No report generated.'
        const repoName = data.repo || 'Repository'
        const subject = encodeURIComponent(`[GITam AI] Engineering Health Report — ${repoName}`)
        const body = encodeURIComponent(reportText)

        // Open default email client with report pre-filled
        window.open(`mailto:${ceoEmail}?subject=${subject}&body=${body}`, '_blank')
        showToast(`Email client opened for ${ceoEmail}!`, 'success')
    }

    const handlePrint = () => {
        window.print()
    }

    const renderReport = (text) => {
        if (!text) return <p style={{ color: 'var(--text-muted)' }}>No report generated.</p>

        const lines = text.split('\n')
        return lines.map((line, i) => {
            // H1
            if (line.startsWith('# ') && !line.startsWith('## ')) {
                return <h1 key={i} style={{ fontSize: '24px', marginBottom: '8px', marginTop: '0' }}>{line.slice(2)}</h1>
            }
            // H2
            if (line.startsWith('## ')) {
                return <h2 key={i}>{line.slice(3)}</h2>
            }
            // H3
            if (line.startsWith('### ')) {
                return <h3 key={i}>{line.slice(4)}</h3>
            }
            // Bullet
            if (line.startsWith('- ') || line.startsWith('* ')) {
                const content = line.slice(2)
                const boldified = content.split(/\*\*(.*?)\*\*/g).map((part, j) =>
                    j % 2 === 1 ? <strong key={j}>{part}</strong> : part
                )
                return <li key={i}>{boldified}</li>
            }
            // Numbered list
            if (/^\d+\.\s/.test(line)) {
                const content = line.replace(/^\d+\.\s/, '')
                const boldified = content.split(/\*\*(.*?)\*\*/g).map((part, j) =>
                    j % 2 === 1 ? <strong key={j}>{part}</strong> : part
                )
                return <li key={i}>{boldified}</li>
            }
            // Empty line
            if (line.trim() === '') return <br key={i} />
            // Paragraph with bold support
            const boldified = line.split(/\*\*(.*?)\*\*/g).map((part, j) =>
                j % 2 === 1 ? <strong key={j}>{part}</strong> : part
            )
            return <p key={i}>{boldified}</p>
        })
    }

    const getScoreColor = (score) => {
        if (score >= 70) return 'var(--color-healthy)'
        if (score >= 40) return 'var(--color-warning)'
        return 'var(--color-critical)'
    }

    return (
        <div className="page">
            <div className="page-header">
                <h1 className="page-title">📋 CEO Business Impact Report</h1>
                <p className="page-subtitle">
                    Generated by AI — translating technical risk into business impact for executive stakeholders
                </p>
            </div>

            <div className="report-container">
                {/* Main report */}
                <div className="report-main">
                    {renderReport(report.report_text)}
                </div>

                {/* Sidebar */}
                <div className="report-sidebar">
                    {/* Metrics cards */}
                    <div className="card">
                        <h3 className="card-title" style={{ marginBottom: '16px' }}>📊 Key Metrics</h3>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                <span style={{ fontSize: '13px', color: 'var(--text-secondary)' }}>Health Score</span>
                                <span style={{ fontWeight: '700', color: getScoreColor(metrics.overall_health) }}>
                                    {Math.round(metrics.overall_health || 0)} ({metrics.grade})
                                </span>
                            </div>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                <span style={{ fontSize: '13px', color: 'var(--text-secondary)' }}>Risk Cost (90d)</span>
                                <span style={{ fontWeight: '700', color: 'var(--color-critical)' }}>
                                    ${(metrics.total_risk_cost || 0).toLocaleString()}
                                </span>
                            </div>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                <span style={{ fontSize: '13px', color: 'var(--text-secondary)' }}>Risk Hours (90d)</span>
                                <span style={{ fontWeight: '700', color: 'var(--color-warning)' }}>
                                    {(metrics.total_risk_hours || 0).toLocaleString()} hrs
                                </span>
                            </div>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                <span style={{ fontSize: '13px', color: 'var(--text-secondary)' }}>High Risk Files</span>
                                <span style={{ fontWeight: '700', color: 'var(--color-critical)' }}>
                                    {metrics.high_risk_components || 0}
                                </span>
                            </div>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                <span style={{ fontSize: '13px', color: 'var(--text-secondary)' }}>Open Bugs</span>
                                <span style={{ fontWeight: '700' }}>{metrics.open_bugs || 0}</span>
                            </div>
                        </div>
                    </div>

                    {/* Email to CEO */}
                    <div className="email-card">
                        <h3>📧 Send to CEO</h3>
                        <input
                            className="input"
                            type="email"
                            placeholder="ceo@company.com"
                            value={ceoEmail}
                            onChange={(e) => setCeoEmail(e.target.value)}
                            id="ceo-email-input"
                        />
                        <button
                            className="btn btn-primary"
                            onClick={sendEmail}
                            disabled={sending}
                            id="send-email-btn"
                        >
                            {sending ? (
                                <>
                                    <span className="spinner" style={{ width: '14px', height: '14px' }}></span>
                                    Sending...
                                </>
                            ) : (
                                '📨 Send Report'
                            )}
                        </button>
                    </div>

                    {/* Print / Export */}
                    <div className="card">
                        <h3 className="card-title" style={{ marginBottom: '12px' }}>🖨️ Export</h3>
                        <button className="btn btn-secondary" onClick={handlePrint} style={{ width: '100%', justifyContent: 'center' }}>
                            Print / Save PDF
                        </button>
                    </div>
                </div>
            </div>

            {/* Toast notification */}
            {toast && (
                <div className={`toast ${toast.type}`}>
                    {toast.type === 'success' ? '✅' : '❌'} {toast.message}
                </div>
            )}
        </div>
    )
}
