"""
Email Sender Agent - Sends CEO reports via email using SMTP.
"""

import os
import io
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from dotenv import load_dotenv
import re
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

load_dotenv()


class EmailSenderAgent:
    """Agent that sends formatted reports via email."""

    def __init__(self):
        self.smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
        self.smtp_port = int(os.getenv("SMTP_PORT", "587"))
        self.sender_email = os.getenv("SMTP_EMAIL", "")
        self.sender_password = os.getenv("SMTP_PASSWORD", "")

    def _markdown_to_html(self, markdown_text: str) -> str:
        """Convert simple markdown to HTML for email."""
        html = markdown_text

        # Headers
        html = re.sub(r'^### (.+)$', r'<h3 style="color:#6366f1;margin-top:20px;">\1</h3>', html, flags=re.MULTILINE)
        html = re.sub(r'^## (.+)$', r'<h2 style="color:#8b5cf6;margin-top:24px;border-bottom:2px solid #e5e7eb;padding-bottom:8px;">\1</h2>', html, flags=re.MULTILINE)
        html = re.sub(r'^# (.+)$', r'<h1 style="color:#1e1b4b;font-size:28px;">\1</h1>', html, flags=re.MULTILINE)

        # Bold
        html = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html)

        # Bullet points
        html = re.sub(r'^- (.+)$', r'<li style="margin-bottom:6px;">\1</li>', html, flags=re.MULTILINE)

        # Wrap consecutive li elements in ul
        html = re.sub(r'((?:<li[^>]*>.*?</li>\s*)+)', r'<ul style="padding-left:24px;">\1</ul>', html, flags=re.DOTALL)

        # Paragraphs
        html = re.sub(r'\n\n', r'</p><p style="line-height:1.6;color:#374151;">', html)

        return f"""
        <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width:700px; margin:0 auto; padding:32px; background:#fafafa; border-radius:12px;">
            <div style="background:linear-gradient(135deg, #6366f1, #8b5cf6); padding:24px 32px; border-radius:12px 12px 0 0; margin:-32px -32px 24px -32px;">
                <h1 style="color:white; margin:0; font-size:24px;">🔍 Hotspot AI</h1>
                <p style="color:#e0e7ff; margin:8px 0 0 0; font-size:14px;">Predictive Engineering Intelligence Report</p>
            </div>
            <p style="line-height:1.6;color:#374151;">{html}</p>
            <div style="margin-top:32px; padding-top:16px; border-top:1px solid #e5e7eb; color:#9ca3af; font-size:12px;">
                Generated by Hotspot AI — Predictive Engineering Intelligence Platform
            </div>
        </div>
        """

    def _markdown_to_plain_lines(self, markdown_text: str) -> list:
        """Convert markdown-ish text into readable plain lines for PDF export."""
        cleaned = markdown_text.replace("**", "")
        cleaned = re.sub(r'^#+\s*', '', cleaned, flags=re.MULTILINE)
        cleaned = re.sub(r'^-\s*', '• ', cleaned, flags=re.MULTILINE)
        cleaned = re.sub(r'^\*\s*', '• ', cleaned, flags=re.MULTILINE)
        return cleaned.splitlines()

    def _build_pdf_attachment(self, report_markdown: str, repo_name: str) -> bytes:
        """Generate a simple PDF version of report for email attachment."""
        buffer = io.BytesIO()
        pdf = canvas.Canvas(buffer, pagesize=letter)
        width, height = letter

        y = height - 48
        left_margin = 48
        max_chars = 105

        pdf.setFont("Helvetica-Bold", 14)
        pdf.drawString(left_margin, y, f"Engineering Health Report - {repo_name}")
        y -= 24

        pdf.setFont("Helvetica", 10)
        for raw_line in self._markdown_to_plain_lines(report_markdown):
            line = raw_line.strip()
            if line == "":
                y -= 8
                if y < 48:
                    pdf.showPage()
                    pdf.setFont("Helvetica", 10)
                    y = height - 48
                continue

            chunks = [line[i:i + max_chars] for i in range(0, len(line), max_chars)]
            for chunk in chunks:
                pdf.drawString(left_margin, y, chunk)
                y -= 14
                if y < 48:
                    pdf.showPage()
                    pdf.setFont("Helvetica", 10)
                    y = height - 48

        pdf.save()
        buffer.seek(0)
        return buffer.read()

    def send_report(self, to_email: str, report_markdown: str, repo_name: str) -> dict:
        """Send the CEO report via email."""
        print(f"[EmailSender] Sending report to {to_email}...")

        if not self.sender_email or not self.sender_password:
            return {
                "success": False,
                "error": "Email not configured. Set SMTP_EMAIL and SMTP_PASSWORD in .env file.",
            }

        try:
            msg = MIMEMultipart("mixed")
            msg["Subject"] = f"🔍 Engineering Health Report: {repo_name}"
            msg["From"] = self.sender_email
            msg["To"] = to_email

            alt = MIMEMultipart("alternative")

            # Plain text version
            text_part = MIMEText(report_markdown, "plain")
            alt.attach(text_part)

            # HTML version
            html_content = self._markdown_to_html(report_markdown)
            html_part = MIMEText(html_content, "html")
            alt.attach(html_part)

            msg.attach(alt)

            # PDF attachment
            pdf_bytes = self._build_pdf_attachment(report_markdown, repo_name)
            pdf_part = MIMEApplication(pdf_bytes, _subtype="pdf")
            pdf_part.add_header(
                "Content-Disposition",
                "attachment",
                filename=f"{repo_name.replace('/', '_')}_engineering_report.pdf",
            )
            msg.attach(pdf_part)

            # Send
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                server.starttls()
                server.login(self.sender_email, self.sender_password)
                server.send_message(msg)

            print(f"[EmailSender] Report sent successfully to {to_email}")
            return {"success": True, "message": f"Report sent to {to_email}"}

        except Exception as e:
            print(f"[EmailSender] Failed to send email: {e}")
            return {"success": False, "error": str(e)}
